# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.runs/synth_1/mfp_nexys4_ddr.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.cache/wt [current_project]
set_property parent.project_path C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  {C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/3rd Party IP/uart-debug/ascii.vh}
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/mfp_ahb_const.vh
}
set_property file_type "Verilog Header" [get_files {{C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/3rd Party IP/uart-debug/ascii.vh}}]
read_verilog -library xil_defaultlib {
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/io/buzzer.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/PulseGenerator.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/io/SPI_Master.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/Start_Div_mul.v
  {C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/3rd Party IP/uart-debug/UART_RX.v}
  {C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/3rd Party IP/uart-debug/UART_TX.v}
  {C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/3rd Party IP/uart-debug/cmdproc.v}
  {C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/3rd Party IP/uart-debug/debug_control.v}
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/dffe.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/dffe3.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/dffe5.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/io/milliscounter.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/mux8x32.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/io/pmod_als_spi_receiver.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/sc_cu.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/sevensegdec.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/io/sevensegtimer.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/uram.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/Basic_and.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/SDivide.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/UDivide.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/alu.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/branch_addr.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RTL/Common/io/cpugpio.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/dffe32.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/imme.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/jal_addr.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/jalr_addr.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/mul_div.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/new/multiplysignedsigned.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/new/multiplysignedunsigned.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/new/multiplyunsignedunsigned.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/mux2x32.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/mux4x32.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/pc4.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/regfile.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/rv32m_fuse.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/RISC-Vrv32m/rv32m_fuseALU.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/sc_computer.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/sccomp_decoder.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/sccpu.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/mfp_nexys4_ddr.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/Documents/cod_riscv_cpu/sc_computer_tb.v
  C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/imports/RISC-Vrv32m/Start_Div.v
}
read_ip -quiet C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/constrs_1/imports/Common/mfp_nexys4_ddr.xdc
set_property used_in_implementation false [get_files C:/JHU_Classes/RISC_V/riscv-cpu/RTL/CPUs/RISCVrv32IM/RISCVrv32IM.srcs/constrs_1/imports/Common/mfp_nexys4_ddr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mfp_nexys4_ddr -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mfp_nexys4_ddr.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file mfp_nexys4_ddr_utilization_synth.rpt -pb mfp_nexys4_ddr_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
